# Generated by Django 5.0.6 on 2024-06-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maxiapp', '0005_alter_proveedorcla_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadocla',
            name='fecha_contratacion',
        ),
    ]
